variables:
    JULIA_DEPOT_PATH: "$CI_PROJET_DIR/.julia"

.test_template: &test_definition
  script:
    - ls -al .julia/packages
    - julia -e 'using Pkg; Pkg.clone(pwd()); Pkg.build("NeRCA"); Pkg.test("NeRCA"; coverage = true)'
    - julia -e 'using Pkg; Pkg.add("Coverage"); 
      import NeRCA; cd(joinpath(dirname(pathof(NeRCA)), ".."));
      using Coverage; cl, tl = get_summary(process_folder());
      println("(", cl/tl*100, "%) covered")'
    - ls -al .julia/packages

cache:
  paths:
    - .julia/packages
  key: "$CI_COMMIT_REF_SLUG"

test:julia-1.0:
  image: docker.km3net.de/base/julia:1.0
  <<: *test_definition

test:julia-1.1:
  image: docker.km3net.de/base/julia:1.1
  <<: *test_definition

test:julia-1.2:
  image: docker.km3net.de/base/julia:1.2
  <<: *test_definition


pages:
  image: docker.km3net.de/base/julia:1.2
  stage: deploy
  script:
    - apt-get update -qq && apt-get install -y git # needed by Documenter
    - julia --project=docs -e '
          using Pkg;
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          include("docs/make.jl");'
    - mv docs/build public # move to the directory picked up by Gitlab pages
  artifacts:
    paths:
      - public
  only:
  - master
